---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: MyApp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 9376
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: MyApp
spec:
  replicas: 10
  selector:
    matchLabels:
      app: MyApp
  template:
    metadata:
      labels:
        app: MyApp
    spec:
      containers:
      - name: app
        image: my-app:1.1.0
        ports:
        - containerPort: 9376
---
bar:
  - missing in a.yaml
---
baz:
  - missing in a.yaml
---
this:
  is:
    the: same
