name: Go
on:
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21
    - uses: actions/checkout@v3

    - run: make bootstrap-tools
    - run: make lint
    - run: make cover

    - uses: codecov/codecov-action@v1
